### ISSUE TITLE
Evaluation of the Maze  for accuracy 

### ISSUE THREAD

**Issue by developeralgo8888** [zhongwen/predictron#12]
are you by any chance going to add evaluation for the predictions of the maze ?

**Comment by zhongwen** [comment]
Please check the response in https://openreview.net/forum?id=BkJsCIcgl, quoted

```
The reported errors were measured on unseen samples (before the network is updated on them).
```

I did it in the same way. Check the appendix for the number of possible mazes, and you can get it.
